# Generated by Django 5.2.8 on 2025-11-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='상품 상태, 사용 기간 등을 자세히 적어주세요.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='가격을 숫자로만 입력하세요. (예: 30000)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='상품 제목을 100자 이내로 입력하세요.', max_length=100),
        ),
    ]
