# Generated by Django 5.2.8 on 2025-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_item_description_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('sale', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='sale', max_length=10),
        ),
    ]
